security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /admin/
            logout:       true
            anonymous:    true

        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        # for convenience, I decided to gather Sonata roles here
        #ROLE_SONATA_FOO_READER:
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_LIST
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_VIEW
        #ROLE_SONATA_FOO_EDITOR:
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_CREATE
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_EDIT
        #ROLE_SONATA_FOO_ADMIN:
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_DELETE
        #    - ROLE_SONATA_ADMIN_DEMO_FOO_EXPORT
        # those are the roles I will use (less verbose)
        ROLE_USER:              [ROLE_USER]
        ROLE_ADMIN:             [ROLE_ADMIN]
        ROLE_SUPER_ADMIN:       [ROLE_SUPER_ADMIN, ROLE_SONATA_ADMIN]

        # set access_strategy to unanimous, else you may have unexpected behaviors
    access_decision_manager:
        strategy: unanimous