services:
    sonata.admin.userelecms:
        class: Elecms\ElecmsBundle\Admin\UserElecmsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Elecms\ElecmsBundle\Entity\UserElecms
            - ~
        calls:
            - [ setTranslationDomain, [ElecmsBundle]]
    sonata.admin.page:
            class: Elecms\ElecmsBundle\Admin\PageAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Page" }
            arguments:
                - ~
                - Elecms\ElecmsBundle\Entity\Page
                - ~
            calls:
                - [ setTranslationDomain, [ElecmsBundle]]