services:
    sonata.admin.post:
        class: Elecms\ElecmsBundle\Admin\UserElecmsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Elecms\ElecmsBundle\Entity\UserElecms
            - ~
        calls:
            - [ setTranslationDomain, [ElecmsBundle]]