elecms_homepage:
    path:     /
    defaults: { _controller: ElecmsBundle:Page:index }

elecms_install:
    path:     /{_locale}/install/
    defaults: { _controller: ElecmsBundle:Install:index }
    requirements:
            _locale: pl|en

elecms_lang_install:
    path:     /install/
    defaults: { _controller: ElecmsBundle:Install:index }

elecms_step:
    path:     /{_locale}/install/{step}
    defaults: { _controller: ElecmsBundle:Install:step }
    requirements:
            step:  \d+
            _locale: pl|en

elecms_page:
    path:     /{_locale}/{page}
    defaults: { _controller: ElecmsBundle:Page:render }
    requirements:
            _locale: pl|en
            page:  "[a-zA-Z1-9\-]+"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme