elecms_homepage:
    path:     /
    defaults: { _controller: ElecmsBundle:Page:index }

elecms_install:
    path:     /{_locale}/install/
    defaults: { _controller: ElecmsBundle:Install:index }
    requirements:
            _locale: pl|en

elecms_lang_install:
    path:     /install/
    defaults: { _controller: ElecmsBundle:Install:index }

elecms_step:
    path:     /{_locale}/install/{step}
    defaults: { _controller: ElecmsBundle:Install:step }
    requirements:
            step:  \d+
            _locale: pl|en

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme