<?php

namespace Elecms\ElecmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserElecmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserElecmsRepository extends EntityRepository
{
}
